"""Secure log snapshot and integrity verification module."""

from __future__ import annotations

import hashlib
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from .monitor import enumerate_processes, format_memory_report
from .security import DATA_DIR, audit_event

LOG_DIR = DATA_DIR / "snapshots"
HASH_SUFFIX = ".sha256"


def ensure_log_dir() -> None:
    LOG_DIR.mkdir(parents=True, exist_ok=True)


def calculate_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(65536), b""):
            h.update(block)
    return h.hexdigest()


def write_hash_file(log_path: Path) -> Path:
    digest = calculate_sha256(log_path)
    hash_path = log_path.with_suffix(log_path.suffix + HASH_SUFFIX)
    hash_path.write_text(f"{digest}  {log_path.name}\n", encoding="utf-8")
    return hash_path


def create_snapshot(user: Dict[str, str], include_restricted_details: bool = False) -> Path:
    """Write a system snapshot and immediately generate a hash file."""
    ensure_log_dir()
    now = datetime.now()
    safe_username = user["username"].replace("/", "_")
    filename = f"snapshot_{now.strftime('%Y%m%d_%H%M%S')}_{safe_username}.log"
    log_path = LOG_DIR / filename

    process_rows = enumerate_processes(include_restricted_details=include_restricted_details, limit=100)

    with log_path.open("w", encoding="utf-8") as f:
        f.write("Secure System Observer Snapshot\n")
        f.write("================================\n")
        f.write(f"Created Timestamp: {now.isoformat(timespec='seconds')}\n")
        f.write(f"Generated By Username: {user['username']}\n")
        f.write(f"Generated By Role: {user['role']}\n")
        f.write(f"Operating System User ID: {os.getuid() if hasattr(os, 'getuid') else 'N/A'}\n")
        f.write("\n")
        f.write(format_memory_report())
        f.write("\n\n")
        f.write("Process Snapshot\n")
        f.write("================\n")
        if include_restricted_details:
            f.write("PID | PPID | STATE | UID | OWNER | NAME | CMDLINE\n")
            for p in process_rows:
                f.write(
                    f"{p['pid']} | {p.get('ppid', '?')} | {p['state_code']} {p['state']} | "
                    f"{p.get('uid', '?')} | {p.get('owner', '?')} | {p['name']} | {p.get('cmdline', '')}\n"
                )
        else:
            f.write("PID | STATE | NAME\n")
            for p in process_rows:
                f.write(f"{p['pid']} | {p['state_code']} {p['state']} | {p['name']}\n")

    hash_path = write_hash_file(log_path)
    audit_event("SNAPSHOT_CREATED", f"Created {log_path.name} with hash {hash_path.name}", user["username"])
    return log_path


def list_logs() -> List[Path]:
    ensure_log_dir()
    return sorted(LOG_DIR.glob("*.log"), key=lambda p: p.stat().st_mtime, reverse=True)


def verify_log(log_path: Path) -> bool:
    hash_path = log_path.with_suffix(log_path.suffix + HASH_SUFFIX)
    if not log_path.exists():
        raise FileNotFoundError(f"Log file not found: {log_path}")
    if not hash_path.exists():
        raise FileNotFoundError(f"Hash file not found: {hash_path}")

    saved_digest = hash_path.read_text(encoding="utf-8").split()[0]
    current_digest = calculate_sha256(log_path)
    return saved_digest == current_digest


def delete_log_pair(log_path: Path, username: str) -> None:
    hash_path = log_path.with_suffix(log_path.suffix + HASH_SUFFIX)
    if log_path.exists():
        log_path.unlink()
    if hash_path.exists():
        hash_path.unlink()
    audit_event("LOG_DELETED", f"Deleted {log_path.name} and matching hash file", username)
